version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate grpc proto file"
    cmds:
       - protoc -I proto proto/main/main.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative