version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate grpc proto file"
    cmds:
     - protoc -I proto proto/*/*.proto --go_out=./pkg/gen/golang --go_opt=paths=source_relative --go-grpc_out=./pkg/gen/golang --go-grpc_opt=paths=source_relative
  nodets:
    aliases:
      - node:ts
    desc: "generate grpc proto file in node js"
    cmds:
     -  npx protoc -I proto proto/*/*.proto  --plugin=./node_modules/.bin/protoc-gen-ts_proto.CMD  --ts_proto_out=pkg/gen/node/ts  --ts_proto_opt=nestJs=true
  nodejs:
    aliases:
      - node:js
    desc: "generate grpc proto file in node js"
    cmds:
      - npx protoc -I proto proto/*/*.proto  --plugin=./node_modules/.bin/protoc-gen-js  --js_proto_out=./



