version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate grpc proto file"
    cmds:
     - protoc -I proto proto/*/*.proto --go_out=./pkg/gen/golang --go_opt=paths=source_relative --go-grpc_out=./pkg/gen/golang --go-grpc_opt=paths=source_relative
